### ISSUE TITLE
Get Rid of Redux for User Preferences/Data

### ISSUE THREAD

**Issue by Arthi-chaud** [Arthi-chaud/Meelo#610]
The wheel was reinvented. Let's take advantage of popular libraries that do the job for us:

- [x] Use MUI's CSS Variables and `useColorScheme` hook to access the current theme (light/dark) (Closed with #609)
- [x] Use `next-i18next` to handle translations and language preferences (Closed with #611)
- [x] Use Local Storage Hook for Notification Preferences (Closed with #617)

---

- [x] Regarding the `UserSlice`, we could get rid of it, and write a custom hook that relies on react-query
