### ISSUE TITLE
[ROADMAP] Rewriting of Videos

### ISSUE THREAD

**Issue by Arthi-chaud** [Arthi-chaud/Meelo#815]
This issue serves as a roadmap for the rewritting of the way we handle videos. It will fix thw following issues:

- #740 
- #767 
- #768
---
### Models

- [x] Videos should be related to a Song group (instead of a song)
- [x] A track can be related to a video (if it is, then the track is an 'instance' of that video)
- [x] TBC: A track can be linked to both a video and song 
- [x] TBC: Videos can have a type (Music Video, Behind-the-Scene, Interview, etc.)

### Registration

- [x] If the video is not a music video, do not create a song with the track's name
- [x] If the track is a video, create a video entry.
- [x] Make sure that titles are parsed correctly.
  - It's most likely that we will have to write an alternative to `extractTrackExtension`
 
### API

- [x] The `/videos` endpoint and related service should use the relations established by the Videos table

### Front

- [x] Use the new `Video` data model
- [x] `/songs/:id/:tab` should have a video section

### Search (#767)
 We should be able to use the search feature with videos

- [x] In a 'Video' tab
- [x] In the 'All' tab

**Comment by Arthi-chaud** [comment]
Closed by #818. Ready for v3
