### ISSUE TITLE
Controllers: Add reassignment routes

### ISSUE THREAD

**Issue by Arthi-chaud** [Arthi-chaud/Meelo#82]
Related tracks/releases might be assigned to distinct parent songs/albums, with variating names.
There should be an easy way to re-assign a resource to a parent.
We should be able to reassign
- [x] Albums (to artist) [see #129] 
- [x] Releases (to album) [see #130}
- [x] Tracks (to song) [see #128]
